

# Database configuration
database:
  active: true
  host: "192.168.0.30"
  port: 3306
  database: "etsUtils"
  username: "etsutils"
  password: "abJ-n5PBGdy4"


default-config:
  player:
    rank: "Member"
    balance: 0

  commands:
    balance: true
    player: true
    pvp: true
    rank: true

  ranks:
  - 1:
    - Admin
  - 10:
    - Mod
  - 20:
    - Builder
  - 30:
    - Member

