
# Database configuration
database:
  active: true
  host: "xdd"
  port: wololo
  database: "name"
  username: "username or something"
  password: "nope :D"


# Default configs
player:
  rank: "mbr"
  pvp: true

# Enable and disable commands (useful for compatibility with other plugins)
# true = command enabled | false = command disabled
commands:
  get: true
  permissions: true
  player: true
  pvp: false
  rank: true

# Automatically created when the plugin is loaded
# Rank names will be stored and accessed in lowercase text
ranks:
  - "admin"
  - "mod"
  - "mbr"
  - "inv"
