

# Database configuration
database:
  active: true
  host: "192.168.0.30"
  port: 3306
  database: "etsUtils"
  username: "etsutils"
  password: "abJ-n5PBGdy4"

ranks:
  100:
    - Admin
  200:
    - Mod
  300:
    - Builder
  400:
    - Member
  500:
    - Guest
